### ISSUE TITLE
Model colors don't change in the randomizer's preview image

### ISSUE THREAD

**Issue by EthanArmbrust** [LagoLunatic/PyFastTextureUtils#3]
Issue starts in 7c9bcf3048678984c7a9a9bfd9578f13c2074a19.  Tested previous commit 2e3cb600d91811ed14505b9a6b6fe58acd0a43ea and it works fine.

**Comment by LagoLunatic** [comment]
Can't reproduce.

What operating system are you testing on? What custom model and colors are you using? What exact command did you use to install PyFastTextureUtils?

**Comment by EthanArmbrust** [comment]
Tested on windows, mac, and linux. 
Installed with `pip install git+git://github.com/LagoLunatic/PyFastTextureUtils@7c9bcf3048678984c7a9a9bfd9578f13c2074a19#egg=PyFastTextureUtils`  

Make sure to uninstall the package through pip first with `pip uninstall pyfasttextureutils`. Pip won't actually update if the version number in the git repository is the same as the currently installed version.

Edit: Forgot to mention I tested it with the default link model and the casual wear. Tried changing colors individually and with the built in presets, but the preview image doesn't change

**Comment by LagoLunatic** [comment]
Odd, not sure why not only pip but even setup.py wouldn't really re-install it. I can reproduce it after uninstalling though.

**Comment by EthanArmbrust** [comment]
Thanks! I think a version bump might be good to prevent the re-install issue.

**Comment by LagoLunatic** [comment]
It shouldn't matter since I forgot to put the bugged commit in wwrando's requirements back then anyway
